### ISSUE TITLE
Cannot load MvcJsonMvcCoreBuilderExtensions' from assembly 'Microsoft.AspNetCore.Mvc.Formatters.Json, Version=6.0.0.0

### ISSUE THREAD

**Issue by ValentinMil** [jlucansky/Quartzmin#56]
Hi,

We have recently updated from .Net Core 2.2 to .Net Core 6.0 and we are getting the error below. 
We were using "Quartz" Version="3.0.7". We have tried also updating to "Quartz" Version="3.5.0" but that did not fix the issue.
Does anyone know if there is a fix for this? 
Thank you!

System.TypeLoadException: 'Could not load type 'Microsoft.Extensions.DependencyInjection.MvcJsonMvcCoreBuilderExtensions' from assembly 'Microsoft.AspNetCore.Mvc.Formatters.Json, Version=6.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'.'

Stack Trace:
   at Quartzmin.ApplicationBuilderExtensions.AddQuartzmin(IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.WebHostBuilder.<>c__DisplayClass10_0.<ConfigureServices>b__0(WebHostBuilderContext _, IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.WebHostBuilder.BuildCommonServices(AggregateException& hostingStartupErrors)
   at Microsoft.AspNetCore.Hosting.WebHostBuilder.Build()
   at Quartzmin.SelfHost.QuartzminPlugin.<Start>d__23.MoveNext()
   at Quartz.Core.QuartzScheduler.<StartPlugins>d__174.MoveNext()
   at Quartz.Core.QuartzScheduler.<Start>d__68.MoveNext()

**Comment by Jetro223** [comment]
Hi @ValentinMil ,

I have the same problem - did you find a solution?

**Comment by dtila** [comment]
Same for .NET 7. From what I see the problem resides the fact this package is referenced but no longer supported 

https://www.nuget.org/packages/Microsoft.AspNetCore.Mvc.Formatters.Json/2.2.0?_src=template

**Comment by dtila** [comment]
The project looks dead. Many PR ready and no code changed since years. 

This project should be downgraded https://github.com/jlucansky/Quartzmin/pull/46
